export enum TipoReuniao {
  DELIBERATIVA = 'DELIBERATIVA',

  INFORMATIVA = 'INFORMATIVA',

  AVALIATIVA = 'AVALIATIVA',

  CRIATIVA = 'CRIATIVA',

  FEEDBACK = 'FEEDBACK',

  RESULTADOS = 'RESULTADOS',
}
